CREATE USER 'airflow'@'%' IDENTIFIED BY 'airflow';
CREATE DATABASE IF NOT EXISTS airflow;
GRANT ALL PRIVILEGES ON airflow.* TO 'airflow'@'%';
CREATE USER 'hive'@'%' IDENTIFIED BY 'hive';
CREATE DATABASE IF NOT EXISTS hive;
GRANT ALL PRIVILEGES ON hive.* TO 'hive'@'%';
FLUSH PRIVILEGES;
